export const formesDefault: string[] = [
  'Comprimé',
  'Gélule',
  'Capsule',
  'Sirop',
  'Solution buvable',
  'Suspension buvable',
  'Poudre orale',
  'Granulés',
  'Crème',
  'Pommade',
  'Gel',
  'Lotion',
  'Collyre (gouttes ophtalmiques)',
  'Gouttes nasales',
  'Spray nasal',
  'Inhalateur',
  'Suppositoire',
  'Ovule',
  'Injectable (ampoule, flacon, seringue préremplie)',
  'Patch transdermique',
  'Implant',
  'Lyophilisat (poudre pour reconstitution)',
  'Comprimé effervescent',
  'Comprimé orodispersible',
  'Sirop pédiatrique'
];